name: user_repository
description:  A Dart package for managing the user domain.

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  formz: ^0.4.1
  google_sign_in: ^5.4.0
  meta:
  storage_services_api:
    path: ../storage_services_api
  equatable: ^2.0.3
  uuid: ^3.0.6
  
dev_dependencies:
  very_good_analysis: ^3.0.1