// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRuFqCKGLoL-k_GEtljuF7KuvRdL3urY',
    appId: '1:593803979728:web:07d6060b5017ef684d27d5',
    messagingSenderId: '593803979728',
    projectId: 'project-hepmap',
    authDomain: 'project-hepmap.firebaseapp.com',
    storageBucket: 'project-hepmap.appspot.com',
    measurementId: 'G-8Y8WRY6JCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgKojL7D7NsLjJ4bskBqURK0xibAB0c5s',
    appId: '1:593803979728:android:fddbacebc3bf93034d27d5',
    messagingSenderId: '593803979728',
    projectId: 'project-hepmap',
    storageBucket: 'project-hepmap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZlxW5GDg1ChF-m9y0SxgixOmn937frVo',
    appId: '1:593803979728:ios:30c125f48858e4484d27d5',
    messagingSenderId: '593803979728',
    projectId: 'project-hepmap',
    storageBucket: 'project-hepmap.appspot.com',
    iosClientId: '593803979728-bmee88kl0r7qs8nsrd9jil0c9jvv351b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackWithIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZlxW5GDg1ChF-m9y0SxgixOmn937frVo',
    appId: '1:593803979728:ios:30c125f48858e4484d27d5',
    messagingSenderId: '593803979728',
    projectId: 'project-hepmap',
    storageBucket: 'project-hepmap.appspot.com',
    iosClientId: '593803979728-bmee88kl0r7qs8nsrd9jil0c9jvv351b.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackWithIo',
  );
}
