// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSXecd-x_PuBmwkfqyzNP_JSlZulxrhg',
    appId: '1:464651141529:web:c07b210b8dc7fec6cd9308',
    messagingSenderId: '464651141529',
    projectId: 'hepmap-fc5e3',
    authDomain: 'hepmap-fc5e3.firebaseapp.com',
    storageBucket: 'hepmap-fc5e3.appspot.com',
    measurementId: 'G-CPNBDE8BEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArU5Ai6VHQkKK2fkjkzYbwWv-yqheVBco',
    appId: '1:464651141529:android:919982d96c809cd0cd9308',
    messagingSenderId: '464651141529',
    projectId: 'hepmap-fc5e3',
    storageBucket: 'hepmap-fc5e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlt4wfX-Zjq9_eTrc6Bdl2AiGQ_aMEf3E',
    appId: '1:464651141529:ios:c0b8213c3babbbf3cd9308',
    messagingSenderId: '464651141529',
    projectId: 'hepmap-fc5e3',
    storageBucket: 'hepmap-fc5e3.appspot.com',
    iosClientId: '464651141529-dgfivnsq8go4g1b9586igt7hpfvs5lh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackWithIo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlt4wfX-Zjq9_eTrc6Bdl2AiGQ_aMEf3E',
    appId: '1:464651141529:ios:c0b8213c3babbbf3cd9308',
    messagingSenderId: '464651141529',
    projectId: 'hepmap-fc5e3',
    storageBucket: 'hepmap-fc5e3.appspot.com',
    iosClientId: '464651141529-dgfivnsq8go4g1b9586igt7hpfvs5lh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackWithIo',
  );
}
