name: storage_services_api
description: A dart package that takes care of firestore storage services

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_storage: ^10.3.1
  uuid: ^3.0.6
  very_good_analysis: ^3.0.1